apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-app-deployment
  labels:
    app: jenkins-k8s-app 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: jenkins-k8s-app
  template:
    metadata:
      labels:
        app: jenkins-k8s-app
    spec:
      containers:
      - name: jenkins-k8s-app 
        image: my-jenkins-k8s-app:latest 
        ports:
        - containerPort: 80 
