apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-app-service
  labels:
    app: jenkins-k8s-app
spec:
  selector:
    app: jenkins-k8s-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
